// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArJoSrF1oN0QSdn-hAETIHjOwEploc1CM',
    appId: '1:816780352750:web:db8aa9e01fc7e972eaa7ff',
    messagingSenderId: '816780352750',
    projectId: 'deliveryapp-493e4',
    authDomain: 'deliveryapp-493e4.firebaseapp.com',
    storageBucket: 'deliveryapp-493e4.appspot.com',
    measurementId: 'G-8BDSNVW8S0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArJoSrF1oN0QSdn-hAETIHjOwEploc1CM',
    appId: '1:816780352750:web:2186d52e54f3a78eeaa7ff',
    messagingSenderId: '816780352750',
    projectId: 'deliveryapp-493e4',
    authDomain: 'deliveryapp-493e4.firebaseapp.com',
    storageBucket: 'deliveryapp-493e4.appspot.com',
    measurementId: 'G-ZWXE7ZSK80',
  );
}
